blank_issues_enabled: false
contact_links:
  - name: Nebula Labs Support
    url: https://discord.gg/tcpcnfxmeQ
    about: Join the Nebula Labs community here!
  - name: Report a security vulnerability
    url: contact@utdnebula.com
    about: Please report security vulnerabilities here.
